"""add media attribution fields

Revision ID: f4a7191d8dcf
Revises: 387606607604
Create Date: 2026-09-19 13:53:22.547276
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f4a7191d8dcf'
down_revision: Union[str, Sequence[str], None] = '387606607604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('author', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('license', sa.String(length=200), nullable=True))
    op.add_column('media', sa.Column('license_url', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('source_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'source_url')
    op.drop_column('media', 'license_url')
    op.drop_column('media', 'license')
    op.drop_column('media', 'author')
    # ### end Alembic commands ###